### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by arm61** [pythoninchemistry/intro_python_chemists#14]
Write a section introducing packages: 

- discuss `pip install` of packages 
- explain package importing 
- explain importing a single module or function from a package

Also discuss the importance of the package infrastructure to the python language.

**Comment by glass-w** [comment]
@arm61 I'm happy to get started with this.

**Comment by arm61** [comment]
Consider yourself assigned.

**Comment by arm61** [comment]
My main tip is **short, sweet and to the point, no waffle**.
