### ISSUE TITLE
Simple plots

### ISSUE THREAD

**Issue by arm61** [pythoninchemistry/intro_python_chemists#20]
Write a section on 1d plotting: 

- `plt.plot()`
- `plt.errorbar()`
- multiple lines on a plot

**Comment by alexsquires** [comment]
Going to get stuck in on this! Happy to hear peoples ideas about what would make for neat chemical examples (although I've got plenty up my sleeve).

**Comment by arm61** [comment]
@alexsquires I know people will have issue with this, but the non-object oriented matplotlib is probably simpler to understand so I would stick with that.

**Comment by bjmorgan** [comment]
@arm61 meaning what? Can you give examples of the two approaches?

**Comment by arm61** [comment]
Non-OO
```
plt.plot(x, y)
plt.xlabel('x')
plt.ylabel('y')
plt.show()
```

Vs. 
OO
```
fig, ax = plt.subplots()
ax.plot(x, y)
ax.set_xlabel('x')
ax.set_ylabel('y')
plt.show()
```

I think the former has a lower cognitive load

**Comment by bjmorgan** [comment]
(related off topic Q: pros and cons for introducing objects and methods after functions? Or do we just ignore all the `foo.bar()’?

**Comment by arm61** [comment]
you mean introducing classes **very** early?

**Comment by bjmorgan** [comment]
Agreed @arm61.

**Comment by bjmorgan** [comment]
> Agreed @arm61.

**Comment by bjmorgan** [comment]
> you mean introducing classes **very** early?

Not necessarily full blown classes, but the idea of *objects* that can have “functions” (*methods*) associated with them. To explain the dot syntax. [this is a discussion for a different thread].

**Comment by arm61** [comment]
Moved that discussion to #46

**Comment by alexsquires** [comment]
Is potential solution to include "OO" plotting in the advanced section? I agree that the title 'simple plotting' for this section lends itself better to "non-OO"

**Comment by arm61** [comment]
Definitely potential for a “Advanced Plotting” section that would do the OO!
