### ISSUE TITLE
Object-oriented programming

### ISSUE THREAD

**Issue by arm61** [pythoninchemistry/intro_python_chemists#23]
Write a section discussing what OOP is.

**Comment by RMeli** [comment]
[A Minimal Molecule API](https://depth-first.com/articles/2020/04/06/a-minimal-molecule-api/) could be a nice chemistry-oriented example for OOP.

**Comment by arm61** [comment]
@RMeli cheers for the suggestion! Let us know if you want to contribute that. No worries if too busy 🙂

**Comment by RMeli** [comment]
@arm61 I'd be up to contribute, but it might take some time.

**Comment by arm61** [comment]
No worries, I will assign you on it but if you find you are too busy just let me know!

**Comment by RMeli** [comment]
@arm61 @j-m-dean this should be fixed by #65 , together with #46
