### ISSUE TITLE
Is LaTeX discussed at all?

### ISSUE THREAD

**Issue by alexsquires** [pythoninchemistry/intro_python_chemists#47]
What is the project position on LaTeX? LaTeX for chemistry in itself it could easily be (and probably is) the subject another book. However it's very useful when it comes to e.g. axes labels, is it going to be introduced anywhere?

**Comment by arm61** [comment]
Let’s leave it out of simple plotting? Advanced plotting could include it though (basically referring to the use of it without in depth coverage).

**Comment by alexsquires** [comment]
Happy with that.

**Comment by bjmorgan** [comment]
I think we can include a “LaTeX cheat sheet” for typical plotting uses, or maybe an appendix (who doesn’t love a good appendix?).

**Comment by arm61** [comment]
One appendix/SI at a time Benjamin
