### ISSUE TITLE
Advanced plotting contents

### ISSUE THREAD

**Issue by alexsquires** [pythoninchemistry/intro_python_chemists#50]
Depending on exactly what goes in `surface_plots` I propose covering:

- object oriented plotting, building towards a figure with multiple subplots
- customizing plots, building towards the concept of an .rc file 
- brief intro to LaTeX, purely in the context of conveying data in matplotlib

**Comment by arm61** [comment]
There is currently a pull request open #53 for the surface plots (#21) so you should be able to get an idea of what is in there.
