### ISSUE TITLE
and_or.ipynb needs mendeleev in requirements.txt

### ISSUE THREAD

**Issue by glass-w** [pythoninchemistry/intro_python_chemists#69]
When running the `and_or.ipynb` notebook the following import requires the `mendeleev` package 
```python 
from periodic_table_20 import periodic_table_20
```
but this is not provided in `requirements.txt`.

**Comment by arm61** [comment]
Well noted, feel free to make a PR with a fix. If not I will deal with it on Monday

**Comment by arm61** [comment]
Closed in #70
