### ISSUE TITLE
Add exercises to functions

### ISSUE THREAD

**Issue by arm61** [pythoninchemistry/intro_python_chemists#7]
Currently there are no `#### Exercise` in the functions section. It would be nice to include some.

**Comment by j-m-dean** [comment]
Potential exercises for functions section:

- calculate relative atomic masses of some elements 
- Energy of a particle in a box
- Gibbs free energy 
- Energy of a spring
- Diatomic vibrational frequency
- Calculate reduced mass
- Centre of mass 1D, 2D, 3D
- Moment of inertia for a diatomic
- Bond order calculation 
- Dalton’s partial pressure law
- Ideal gas and VDW equations
- Rydberg equation
- Boltzmann ratio of two energy levels

Most of these you already covered in the [4th year course](https://github.com/pythoninchemistry/ch40208). All fairly simple calculations.
