### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RMeli** [pythoninchemistry/intro_python_chemists#81]
Should a (permissive) license be added to this repository?

**Comment by arm61** [comment]
Weird, I had overlooked that somehow. 

My preference would be CC-BY but will happily hear other thoughts?

**Comment by RMeli** [comment]
CC BY is what I had in mind as well. I also like CC BY-SA in theory, but in practice its "viral" nature might be annoying.

Does CC licenses also apply to the code?

**Comment by arm61** [comment]
Yeah CC BY is more _permissive_ than CC BY-SA (hence my leaning that way). 

I have seen people use something like CC BY for the content of the book, and MIT (for example) for any code samples which is probably the best option...
